### ISSUE TITLE
in my_agent.py you are importing agent module but you have not provided that file.

### ISSUE THREAD

**Issue by sparshgarg23** [luisgaboardi/Motion-Planning-Carla-Simulator#3]
agent.navigation.localplanner module does not exist

**Comment by luisgaboardi** [comment]
Hi! @sparshgarg23 ,  When you put the my_agent file in the path **carla-simulator/PythonAPI/carla/agents/navigation**, there is already a python file there named agent.py.

To reference, I installed CARLA with apt package on Ubuntu 18.04. I don't know if the folder structure changes if its built or on Windows, but I can try to help you run it.

For the agent file:
![Screenshot from 2021-05-18 18-26-14](https://user-images.githubusercontent.com/45673358/118725609-8d9b1e80-b806-11eb-8bc5-c7ad30698d5b.png)

For the motion_planning script:
![Screenshot from 2021-05-18 18-25-31](https://user-images.githubusercontent.com/45673358/118725533-72301380-b806-11eb-8c95-8cfd9915d86d.png)

The imported modules should work if the files are in the correct folder
